/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111159-g1617d1a752-20230619"
#endif /* AVUTIL_FFVERSION_H */
